global:
  scrape_interval:     5s

scrape_configs:
  - job_name: 'order'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['spring-order:8080']
  - job_name: 'invoicing'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['spring-invoicing:8080']
  - job_name: 'shipping'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['spring-shipping:8080']
