version: '3.4'

services:
  postgres-spring:
    image: spring-microservices/postgres
    container_name: spring-postgres
    ports:
      - "5432:5432"
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
  spring-order:
    image: spring-microservices/order
    container_name: spring-order
    ports:
      - "18081:8080"
    links:
      - postgres-spring
      - zipkin
    build:
      context: ./microservice-spring-order
      dockerfile: Dockerfile
    environment:
      FAILRANDOMLY: "true"
  spring-shipping:
    image: spring-microservices/shipping
    container_name: spring-shipping
    ports:
      - "18083:8080"
    links:
      - postgres-spring
      - spring-order
      - zipkin
    build:
      context: ./microservice-spring-shipping
      dockerfile: Dockerfile
  spring-invoicing:
    image: spring-microservices/invoicing
    container_name: spring-invoicing
    ports:
      - "18082:8080"
    links:
      - postgres-spring
      - spring-order
      - zipkin
    build:
      context: ./microservice-spring-invoicing
      dockerfile: Dockerfile
  prometheus:
    image: spring-microservices/prometheus
    container_name: spring-prometheus
    ports:
      - "9090:9090"
    links:
      - spring-order
      - spring-invoicing
      - spring-shipping
    build:
      context: ./prometheus
      dockerfile: Dockerfile
  grafana:
    image: 'grafana/grafana:10.2.0'
    links:
      - prometheus
    ports:
      - '3000:3000'
  zipkin:
    image: openzipkin/zipkin:2.24
    ports:
      - 9412:9411
