name: Build Docker Images for the Microservices

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docker-images:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Compile microservices with Maven
      run: cd microservice-spring-demo && mvn -B package
    - name: Create Docker images
      run: cd microservice-spring-demo && docker-compose build